image: gitpod/workspace-full

tasks:
    - name: install liboqs
      before: 
        sudo apt install -y astyle cmake gcc ninja-build libssl-dev python3-pytest python3-pytest-xdist unzip xsltproc doxygen graphviz python3-yaml valgrind
        && echo "installed liboqs dependencies..."
        && git clone -b main https://github.com/open-quantum-safe/liboqs.git
        && cd liboqs
      command: mkdir build && cd build
        && cmake -GNinja -DBUILD_SHARED_LIBS=ON ..
        && ninja